# Generated by Django 3.2.7 on 2021-09-22 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_dog', models.IntegerField()),
                ('total_cat', models.IntegerField()),
                ('workers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='our_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shelter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PetAdoption.shelter')),
            ],
        ),
        migrations.CreateModel(
            name='dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('img', models.ImageField(upload_to='img/')),
                ('shelter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PetAdoption.shelter')),
            ],
        ),
        migrations.CreateModel(
            name='cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('img', models.ImageField(upload_to='img/')),
                ('shelter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PetAdoption.shelter')),
            ],
        ),
    ]
