# Generated by Django 3.2.7 on 2021-09-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetAdoption', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='name',
        ),
    ]
