# Generated by Django 3.2.7 on 2021-09-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetAdoption', '0002_auto_20210922_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
