# Generated by Django 3.2.7 on 2021-09-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetAdoption', '0004_auto_20210923_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='tittle',
        ),
    ]
