# Generated by Django 4.0.1 on 2022-10-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetAdoption', '0007_address_category_pet_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='shelter',
        ),
        migrations.RemoveField(
            model_name='our_team',
            name='shelter',
        ),
        migrations.DeleteModel(
            name='cat',
        ),
        migrations.DeleteModel(
            name='dog',
        ),
        migrations.DeleteModel(
            name='our_team',
        ),
    ]
