# Generated by Django 4.0.1 on 2022-10-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetAdoption', '0008_remove_dog_shelter_remove_our_team_shelter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registeration',
        ),
    ]
